


---
 
-  name: deploying laravel application
   hosts: all
   become: yes

   tasks:
    


    - name: set timezone to Africa/Lagos
      command: timedatectl set-timezone Africa/Lagos




    - name: set ntp sync to true
      command: timedatectl set-ntp true

    - name: Install Apache2 Server
      apt:
        name: apache2
        state: present
           
 
    
    - name: ufw allow port 80
      ufw:
          rule: allow
          port: '80'
          proto: tcp
   

    - name: ufw allow port 443
      ufw:
          rule: allow
          port: '443'
          proto: tcp


    - name: ufw allow port 22 
      ufw:
         rule: allow
         port: '22'
         proto: tcp
   
    - name: Install git
      apt:
       name: git
       state: present



    - name: Install zip
      apt:
       name: zip
       state: present



    - name: Install unzip
      apt:
       name: unzip
       state: present



    - name: Install curl
      apt:
       name: curl
       state: present
     



    - name: Update installed packages
      ansible.builtin.apt:
            update_cache: yes
            autoremove: yes
            cache_valid_time: 3600
  


    - name: Install lsb-release apt-transport-https ca-certificates
      apt: name={{ item }} state=latest
      loop: [ 'lsb-release', 'apt-transport-https', 'ca-certificates' ]
   


    - name: delete a file if it exists
      file:
         path: /etc/apt/trusted.gpg.d/php.gpg
         state: absent
   
    - name: Download PPA for PHP8.1
      get_url:
          url: https://packages.sury.org/php/apt.gpg
          dest: /etc/apt/trusted.gpg.d/php.gpg
   



    - name: Add the PPA to the server packages
      shell: echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list


    
    - name: install  php library
      command: apt  install -y php8.0 libapache2-mod-php8.0 php8.0-common php8.0-mysql php8.0-xml php8.0-xmlrpc php8.0-curl php8.0-gd php8.0-imagick php8.0-cli php8.0-dev php8.0-imap php8.0-mbstring php8.0-soap php8.0-zip php8.0-intl 
      become: yes



    - name: install  php prerequsites
      command: apt install software-properties-common
    

   
     
    - name: install  php library
      command: apt  install -y php8.1-cli php8.1-soap  php8.1-common php8.1-mysql php8.1-zip php8.1-gd php8.1-mbstring php8.1-curl php8.1-xml php8.1-bcmath
      become: yes

     

    

    

   
#    - name: create mysql database
 #     mysql_db:
  #         name: test-db
   #        login_unix_socket: /var/run/mysqld/mysqld.sock
    #       login_user: user
     #      state: present 
   





    - name: download composer installer
      command: curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
   


    - name: download composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php


      


#    - name: rename composer executable
 #     shell: cp /usr/local/bin/composer.phar /usr/local/bin/composer
     


    - name: Create website directory
      file:
         path: "/var/www/dimmahydriah.me"
         state: directory
         owner:  root
         mode: '0775'
 

    - name: clone laravel repository
      git:
          repo: https://github.com/f1amy/laravel-realworld-example-app.git
          dest: /var/www/myapp
          clone: yes      
          force: yes
     
  
   

    - name: take ownership of myapp folder
      file:
        path: /var/www/myapp
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
    
    - name: set permissions for Laravel storage folder
      file:
        path: /var/www/myapp/storage
        state: directory
        recurse: yes
        mode: '775'

    - name: set permissions for Laravel bootstrap
      file:
        path: /var/www/myapp/bootstrap/cache
        state: directory
        recurse: yes
        mode: '775'

    

    - name: install laravel dependencies
      command: composer update --ignore-platform-reqs
      args:
         chdir: /var/www/myapp
      environment:
         COMPOSER_NO_INTERACTION: '1'
      become: no
 

#    - command: composer update --ignore-platform-reqs 
  
    - name: copy apache config
      copy:
          src: config/myapp.conf
          dest: /etc/apache2/sites-available/myapp.conf
          owner:  "{{ ansible_effective_user_id }}"
          group:  "{{ ansible_effective_user_id }}"
          mode: '0644'


    - name: copy env file
      copy:
         src: /var/www/myapp/.env.example
         remote_src: yes
         dest: /var/www/myapp/.env
         owner: www-data
         group: www-data
         mode: '0644'
     
 
    - name: set server name
      replace:
           path: /etc/apache2/sites-available/myapp.conf
           regexp: '$SERVER_NAME'
           replace: www.dimmahydriah.me 


    - name: enable the new config
      shell: |
          a2ensite myapp.conf
          a2dissite 000-default.conf
          a2enmod rewrite
          service apache2 restart


          
   
    - name: setup laravel
      shell: |
          cd /var/www/myapp
          php artisan key:generate



  
